Catch clause must take only `const` or mutable exceptions

In 2.104, throwing qualified types was
[deprecated](https://dlang.org/changelog/2.104.0.html#dmd.throw-qualifier).

It is also unsafe to catch an exception as `immutable`, `inout` or `shared`.
This is because the exception may still be accessible through another
mutable or non-shared reference. Catching an exception with those qualifiers
is now deprecated.

---
auto e = new Exception("first");
try {
        throw e;
} catch(immutable Exception ie) { // now an error
        e.msg = "second";
        assert(ie.msg == "first"); // would fail
}
---
